name: Generate DocC
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  Build-Github-Actions:
    runs-on: macos-12
    steps:
    - name: Git Checkout main
      uses: actions/checkout@v3

    - name: Git Checkout docs
      uses: actions/checkout@v3
      with:
        ref: docs
        path: docs

    - name: Build Doc Bundle
      run: |
          echo "Building Documentation..."
          xcodebuild docbuild -scheme MGNetworking -derivedDataPath ./docbuild -destination 'platform=macOS' > build_output.txt
          # Uncomment to see build output
          # cat build_output.txt

          # Find documentation inside docbuild
          DOCC_DIR=`find ./docbuild -type d -iname "MGNetworking.doccarchive"`

          # Pretty print DocC JSON output so that it can be consistently diffed between commits
          export DOCC_JSON_PRETTYPRINT=YES

          # Export docs
          echo "Exporting Documentation ..."
          $(xcrun --find docc) process-archive \
          transform-for-static-hosting "$DOCC_DIR" \
          --output-path ./docs/docs \
          --hosting-base-path MGNetworking

    - name: Commit
      id: commit
      run: |
          # Save the current commit we've just built documentation from in a variable
          CURRENT_COMMIT_HASH=`git rev-parse --short HEAD`

          # Commit and push our changes to the gh-pages branch
          cd docs
          git add docs

          if [ -n "$(git status --porcelain)" ]; then
              echo "Documentation changes found. Commiting the changes to the 'docs' branch and pushing to origin."
              git commit -m "Update GitHub Pages documentation site to '$CURRENT_COMMIT_HASH'."
              git push origin HEAD:docs
          else
            # No changes found, nothing to commit.
            echo "No documentation changes found."
          fi
